### ISSUE TITLE
MicrosoftImageRegion.cs - culture bug

### ISSUE THREAD

**Issue by michaelschwarz** [DustyTools/fotofly#1]
The RectangleString is using Double.ToString and Convert.ToDouble without the NumberFormatInfo.InvariantInfo, this will throw an Exception when using i.e. German culture.

Convert.ToDouble(splitString[...])  =>  Convert.ToDouble(splitString[...], NumberFormatInfo.InvariantInfo)

this.Left.ToString()  =>  this.Left.ToString(NumberFormatInfo.InvariantInfo)

This must be changed for all four Double values (Left, Top, Width, Height).

**Comment by DustyTools** [comment]
Thanks for the fix!
