### ISSUE TITLE
Can't build project in VS express 2013

### ISSUE THREAD

**Issue by AndrewM-** [DustyTools/fotofly#5]
The projects load then unload with an error message stating that VS 2013 does not support that type of project.  I can open the project in the latest version of SharpDevelop but cannot build it, something about not being able to support 64-bit debugging.  Nor can I set options to build it as a 32 bit program.   I build it without the debugger but the application crashed on launch.  That is a shame as it looks like a good project.  Taasss, if you are still there, could just refresh the source code so that it can open and build in the current copy of VS and/or SharpDevelop.
Cheers,
Andrew

**Comment by DustyTools** [comment]
Sorry I never looked at this, should work now....
